### PR TITLE
Raise error on missing translations in dev and test.

### LINKED ISSUE #142: Raise error on missing translations in dev/test
By default, we should modify the configuration for the dev and test environments so that an exception is raised should a translation be missing, rather than relying on the fallback. Set `config.action_view.raise_on_missing_translations = true`.

### PR DESCRIPTION
**Pull request by reese**
Resolves #142 

This PR adds `config.action_view.raise_on_missing_translations = true` to the default config files for `dev` and `test`. This will throw errors for missing translations instead of using fallbacks by default.

This PR also removes the `chromedriver-helper` gem from the generated Gemfile, as this causes errors when running on CI. Regardless, that gem is deprecated, _and_ we instruct the user to install chromedriver in the post-install message anyways.

### CODE REVIEW

File: gnarly.rb [hunk 1]
```diff
@@ -270,6 +276,21 @@ def setup_readme
   gsub_file "README.md", "__application_name__", app_name
 end
 
+def setup_i18n
+  missing_translation_config = <<-CONFIG
+
+  # Raise error when missing i18n translations
+  config.action_view.raise_on_missing_translations = true
```
Comment (kevin-j-m) [inline gnarly.rb]: I *believe* this should already be in these files, but commented out.

Comment (reese) [reply gnarly.rb]: It is! I thought that was the case but must have missed it when I searched for it before. I'll change this to just `gsub` the comment out instead.

File: gnarly.rb [hunk 2]
```diff
@@ -188,6 +189,10 @@ def limit_test_logging
   end
 end
 
+def remove_chromedriver_helper
+  gsub_file "Gemfile", /(\s+#.*\s+)gem 'chromedriver-helper'/, ""
+end
```
Comment (kevin-j-m) [inline gnarly.rb]: Rails 6 [removed this](https://github.com/rails/rails/commit/895edbcf406acfe1684bd41a4e3fb901b2ad6d6c) in favor of `webdrivers`. Maybe I'm getting ahead of myself here with #143, but perhaps we can...not care about this?

File: gnarly.rb [hunk 3]
```diff
@@ -270,6 +276,19 @@ def setup_readme
   gsub_file "README.md", "__application_name__", app_name
 end
 
+def setup_i18n
```
Comment (kevin-j-m) [inline gnarly.rb]: Do you think we should be more specific in the name of this method? Just thinking that even without this - your rails app is going to have i18n set up just fine. `configure_i18n`? `raise_on_missing_translations`?

File: gnarly.rb (hunk 2 above)
Comment (reese) [reply gnarly.rb]: We can ignore it for now, but that would mean _also_ not caring about having failing CI, which is why this is here at all. We _could_ close this PR and postpone it until #143 gets completed?

Comment (kevin-j-m) [reply gnarly.rb]: Ok, nevermind, I very much care about CI passing.

Comment (kevin-j-m) [reply gnarly.rb]: Just out of curiosity, what is the CI error with this in there now?

Comment (reese) [reply gnarly.rb]: If you leave it in, you get this error:
```
Selenium::WebDriver::Error::SessionNotCreatedError:
session not created: This version of ChromeDriver only supports Chrome version 76
```

Pretty much every recommendation from the CircleCI forums was to remove `chromedriver-helper` from the Gemfile.
